import {
  Button,
  Container,
  TextInput,
  Textarea,
  Title,
} from '@mantine/core';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useIntl } from 'react-intl';
import styles from '../styles/Contato.module.scss';

const Contato: NextPage = () => {
  const { formatMessage } = useIntl();

  return (
    <>
      <Head>
        <title>Contato</title>
        <meta
          content="Generated by create next app"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <Container>
          <Title
            order={1}
            style={{
              paddingBottom: '10px',
            }}
          >
            Contato
          </Title>
          <TextInput
            className={styles.input}
            label="Full name"
            placeholder="Your name"
            radius="xs"
            required
            size="lg"
          />
          <TextInput
            className={styles.input}
            label="Email"
            placeholder="Your name"
            radius="xs"
            required
            size="lg"
          />
          <TextInput
            className={styles.input}
            label="Telefone"
            placeholder="Your name"
            radius="xs"
            size="lg"
          />
          <TextInput
            className={styles.input}
            label="Cidade"
            placeholder="Your name"
            radius="xs"
            size="lg"
          />
          <TextInput
            className={styles.input}
            label="Assunto"
            placeholder="Your name"
            radius="xs"
            required
            size="lg"
          />
          <Textarea
            className={styles.input}
            label="Your comment"
            minRows={5}
            placeholder="Your comment"
            radius="xs"
            required
            size="lg"
          />
          <Button color="green" radius="xs" size="md" uppercase>
            Submit
          </Button>
        </Container>
      </main>
    </>
  );
};

export default Contato;
