import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.scss';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta
          content="Generated by create next app"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <div
          style={{
            backgroundImage: `url(./main.jpeg)`,
            backgroundPosition: 'center',
            backgroundSize: 'cover',
            backgroundRepeat: 'no-repeat',
            height: '40vh',
            width: '100%',
          }}
        >
          <div className={styles.hero}>Light Steel Frame</div>
        </div>
        <section className={styles.section}>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit.
          Possimus quidem architecto eligendi suscipit magnam iusto
          consequatur. Facere dicta maxime aperiam corrupti in
          aspernatur, eum, voluptas iure earum dolor laudantium
          eligendi!
        </section>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
